FROM python:3.12

RUN apt-get update && apt-get install -y --no-install-recommends shellcheck

ENV \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  PATH="${PATH}:${HOME}/root/.mercado"

WORKDIR /app
COPY Makefile poetry.lock pyproject.toml /app/
COPY hack/deps.sh /app/hack/deps.sh

RUN make deps

COPY . /app
