services:
  test:
    build:
      context: .
      dockerfile: build.Dockerfile
      network: host
    environment:
      - TEST
      - TEST_FUNC
      - LOGLEVEL
      - GITHUB_TOKEN

      # Supporting AppImage artifacts in docker
      # https://github.com/AppImage/AppImageKit/issues/912#issuecomment-528669441
      - APPIMAGE_EXTRACT_AND_RUN=1
    volumes:
      - ${PWD}:/app
