name: Release
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        make deploy
